#!/bin/zsh

# Ensure environment loads first
if [[ -e "${DOTFILES_DIR}/profile/env" ]]; then
  source "${DOTFILES_DIR}/profile/env"
fi

# Custom local profile that should exist outside of the repo
if [[ -e "$HOME/.profile.local" ]]; then
  source "$HOME/.profile.local"
fi

if [[ -d "$DOTFILES_DIR/profile/profile.d" ]]; then
  for file in $(find $DOTFILES_DIR/profile/profile.d -depth 1 -type f | sort); do
	source "${file}"
  done
fi
