#!/bin/zsh
local -a search_dirs

if [[ -e "${CODE_DIR}" ]]; then
  search_dirs+=("${CODE_DIR}")
fi

for depth in {3..5}; do
  local output=$(find ${search_dirs[@]} -mindepth $depth -maxdepth $depth -type d -path "*/$1" -print -quit)
  if [[ -n "${output}" ]]; then
    echo "${output}"
    return 0
  fi
done

return 1
