#!/bin/zsh
#-----------------------------------------------------------------------------
# Syntax highlighting with less
#-----------------------------------------------------------------------------
less -f -x2 <(type pygmentize &>/dev/null && pygmentize -f terminal "$1" || cat "$1")
