#!/bin/zsh
#-----------------------------------------------------------------------------
# Total line count for source files of a given type
#-----------------------------------------------------------------------------
local TYPES
TYPES=$(echo "$@" | sed 's/ /" -or -name "*./g')
TYPES="-name \"*.$TYPES\""
eval "find . $TYPES" | _count_lines
