#!/bin/zsh
#-----------------------------------------------------------------------------
# Generates a PNG for a given LaTeX math formula
#-----------------------------------------------------------------------------
local fname=${3:-formula.png}
local url=$(python -c 'import urllib,sys;print urllib.quote(sys.argv[1])' "$1")
url="http://latex.codecogs.com/png.latex?\\dpi\{${2:-150}\}&$url"
curl "$url" --silent -o "${fname%.png}.png"
