# If inside tmux and closing off last shell in a session, switch to another
num_panes="$(tmux list-panes | wc -l)"
num_windows="$(tmux list-windows | wc -l)"
num_sessions="$(tmux list-sessions | wc -l)"
if [[ -n "${TMUX}" && "${num_panes}" -eq 1 && "${num_windows}" -eq 1 && "${num_sessions}" -gt 1 ]]; then
  tmux switch-client -n
fi
