# If inside tmux and closing off last shell in a session, switch to another
if [[ -n "${TMUX}" && $(tmux list-windows | wc -l) -eq 1 && $(tmux list-sessions | wc -l) -gt 0 ]]; then
  tmux switch-client -n
fi
