# Speed up ZSH initialization by skipping global completion initialization
skip_global_compinit=1

export PATH="/usr/local/bin:${HOME}/bin:${PATH}"

if [[ -f "${HOME}/.zshenv.local" ]]; then
  source "${HOME}/.zshenv.local" 
fi
