#!/bin/bash

# I know, I know... But there's unlikely to be anything zsh-ish in there!
if [[ -e "$HOME/.zshenv" ]]; then
  source "$HOME/.zshenv"
fi

if [[ -e "$HOME/.profile" ]]; then
  source "$HOME/.profile"
fi
